export enum GlobalTypes {
  GLOBAL_GET_APP_ORDER = "GLOBAL_GET_APP_ORDER",
  GLOBAL_EDIT_APP_ORDER = "GLOBAL_EDIT_APP_ORDER",

  GLOBAL_GET_USER_INFO = "GLOBAL_GET_USER_INFO",
  GLOBAL_EDIT_USER_INFO = "GLOBAL_EDIT_USER_INFO",

  GLOBAL_GET_ORG_INFO = "GLOBAL_GET_ORG_INFO",

  GLOBAL_UPDATE_ORG_INFO = "GLOBAL_UPDATE_ORG_INFO",

  GLOBAL_LOGIN_OUT = "GLOBAL_LOGIN_OUT",
}
