 
name: Node CI
on: [push] 
jobs:
  lint-and-test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
     matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@master
    - name: Install
      uses: CultureHQ/actions-yarn@master
      with:
        args: install
    - name: Lint
      uses: CultureHQ/actions-yarn@master
      with:
        args: lint
    - name: Test
      uses: CultureHQ/actions-yarn@master
      with:
      args: test
   env:
    CI: true
